server:
    port: 8080

#路径最后边的/一定不能省略
upload-file-path: D:/upload-file/

#spring
spring:
  session:
     store-type: none
  devtools:
    restart:
      enabled: true        #这里是为了热部署的，与mybatis是无关的
  messages: #国际化
      basename: i18n/messages,i18n/ValidationMessages
  mvc: # 捕获404
      throw-exception-if-no-handler-found: true
  resources:
   add-mappings: false
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  http:
    encoding:
      enabled: true
      charset: UTF-8
  aop:  #使用CGLIB来实现AOP的时候
     proxy-target-class: true

  #DATABASE CONFIG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.50.30:3306/cms?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.guangsoft.web.modules.*.entity  #这里是实体类的位置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  io.guangsoft.web.modules.*.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型

#shiro
cms:
  shiro:
    sessionIdCookieName: sessionId
    #无论是驼峰还剩这种方式，都会被识别成驼峰标识的JavaBean属性
    filter-chain-definitions: /static/**=anon;/upload/**=anon;/jcaptcha*=anon;/login=jCaptchaValidate,authc;/logout=logout;/**=user,sysUser,onlineSession,perms,roles
  admin:
    url:
      prefix: /cms
      suffix: .html
#定时任务配置
quartz:
  open-cluster: false # 是否开启集群
  config-location: /quartz/quartz.properties # 集群配置文件路径
  data-source: qzDS # 集群数据库，使用当前数据库可以设置为空或者default

#swagger配置
swagger:
  enabled: true
  title: 接口文档
  description:
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl:
  contact.name:
  contact.url:
  contact.email:
  base-package: io.guangsoft.web
  base-path: /**
  exclude-path: /error, /ops/**