#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.50.30:3306/cms?useUnicode=true&characterEncoding=UTF-8
    #这里是配置druid连接池，以下都是druid的配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      async-init: true
  thymeleaf:
    cache: false
    enabled: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

#servlet
server:
    port: 8080
    servlet:
        context-path: /media
        session:
          tracking-modes: cookie
          cookie:
            http-only: true

#log4j
logging:
  config: classpath:log4j2.yml

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: io.guangsoft.web.modules.*.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

#swagger配置
swagger:
  enabled: true
  title: MEDIT_API
  description:
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl:
  contact.name:
  contact.url:
  contact.email:
  base-package: io.guangsoft.web
  base-path: /**
  exclude-path: /error, /ops/**